name: Release

on:
  push:
    tags:
      - 'v*'
    branches-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: get_tag
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Build linux amd64
      id: build_exe
      run: 'GOOS=linux GOARCH=amd64 go build -o terraform-provider-git-${{ steps.get_version.outputs.VERSION }} src/*'
      outputs:
        exe_name: terraform-provider-git-${{steps.get_version.outputs.VERSION }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_tag.outputs.VERSION }}
        release_name: ${{ steps.get_tag.outputs.VERSION }}
        body: Test release
        draft: false
        prerelease: false
    - name: Upload linux amd64
      id: upload_linux_amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./${{steps.build_exe.outputs.exe_name }}
        asset_name: ${{steps.build_exe.outputs.exe_name }}
        asset_content_type: application/octet-stream
