name: Release

on:
  push:
    branches:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get version
      id: get_version
      run: |
        echo ::set-output name=version::"${GITHUB_REF/refs\/heads\//}"
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Download dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: go get
    - name: Build linux amd64
      id: build_exe
      env:
        EXE_NAME: terraform-provider-git_${{ steps.get_version.outputs.version }}
      run: |
        echo "Building $EXE_NAME..."
        GOOS=linux GOARCH=amd64 \
          go build \
          -o "$EXE_NAME" \
          -ldflags "-linkmode external -extldflags -static" -a \
          src/*
        echo ::set-output name=exe_name::"$EXE_NAME"
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: ${{ steps.get_version.outputs.version }}
        body: Test release
        draft: false
        prerelease: false
    - name: Upload linux amd64
      id: upload_linux_amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./${{steps.build_exe.outputs.exe_name }}
        asset_name: ${{steps.build_exe.outputs.exe_name }}
        asset_content_type: application/octet-stream
